server:
  port: 9502
spring:
  profiles:
    active: dev
  application:
    name: user-service

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    port: 6379
    host: localhost
    password: licona-erp-redis-password
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/licona_erp?serverTimezone=GMT%2B8&useAffectedRows=true
    username: root
    password: licona-erp-mysql-password
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath:plj/licona/club/user/mapper/xml/*.xml