server:
  port: 9201
  servlet:
    context-path: /licona-erp
spring:
  profiles:
    active: dev
  application:
    name: pwb-gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowCredentials: true
            allowedMethods: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      # 配置路由路径
      routes:
        - id: uaa
          uri: lb://uaa
          predicates:
            - Path=/licona-erp/auth/**
          filters:
            - StripPrefix=2
        - id: acl-service
          uri: lb://acl-service
          predicates:
            - Path=/licona-erp/acl/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/licona-erp/user/**
          filters:
            - StripPrefix=1
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true

  security:
    oauth2:
      resourceserver:
        jwt:
          # 配置RSA的公钥访问地址
          jwk-set-uri: 'http://localhost:9401/rsa/publicKey'
  redis:
    port: 6379
    host: localhost
    password: licona-erp-redis-password

secure:
  ignore:
    # 配置白名单路径
    urls:
      # 认证登录接口
      - "/licona-erp/auth/oauth/token"
      # 用户注册接口
      - "/licona-erp/user/register"


